version: '3'
services:
  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: contenedor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234      
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my_network

node_app:
    image: yohanapotel15/mi_t:1.0
    container_name: conteiner_crud
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - my_network



volumes:
  mysql_data:

networks:
  my_network:
